language: android
sudo: false
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

cache:
  directories:
    - $HOME/.gradle/caches/2.11
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - rm /home/travis/.gradle/caches/2.11/plugin-resolution/cache.properties.lock

after_success:
  - ./gradlew jacocoFullReport

after_failure:
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_script:
  # print lint results details
  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
  - for f in data/build/outputs/lint-results.html; do pandoc $f -t plain; done
