language: android
sudo: false
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install:
  - pip install --user codecov

script:
  - sh ci.sh

after_success:
  - ./gradlew jacocoFullReport
  - codecov

after_failure:
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_script:
  # print lint results details
  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
  - for f in data/build/outputs/lint-results.html; do pandoc $f -t plain; done
